### PR TITLE
Added the addPoints method to the flannlib and pyflann bindings

### PR DESCRIPTION
**Pull request by abramhindle**
Updated COPYING with contribution
Updated pyflann bindings with add_points
Updated flann.h with CXX bindings

Basically I just mixed save_index and build_index into some ugly code that
provided the necessary bindings.

Then I provided some python code which showed that it worked.

### CODE REVIEW

**Comment by Erotemic** [comment]
Is this extremely useful feature planned to be merged in at some point? Is there something I can help with to get this patch merged into the main library?

**Comment by t3476** [comment]
It's useful feature from now. According to Deepmind's paper [Scaling Memory-Augmented Neural Networks with Sparse Reads and Writes
](https://arxiv.org/abs/1610.09027), to make MANN with enormous memory slots efficient, it requires the ability to insert points incrementally.

**Comment by abramhindle** [comment]
The C++ functionality of add_points has already been added, but the python changes need to be merged. I don't have time to do this, but @t3476 you can copy the python portion of the commit and it should work.

**Comment by Erotemic** [comment]
Be careful though, you need to keep a reference to the numpy array that you use to add the points. Otherwise, FLANN might segfault. My fork of FLANN that incorporates these bindings does this for you.

**Comment by jimkon** [comment]
It would be great to finally have the full functionality of the C++ in python too. Not only addPoint, but removePoint and getPoint too. Is it about to happen or better find another walkaround to this?

**Comment by abramhindle** [comment]
I do not have time to address this in newer versions of FLANN 4 years later.
Changes to index.py are probably easy to apply. Someone else can make a new pull request.

**Comment by abramhindle** [comment]
Great! thanks @jannikboll .

**Pull request closed without merging**
